### ISSUE TITLE
Update but don't replace

### ISSUE THREAD

**Issue by cheapsteak** [Experience-Monks/url-set-query#1]
If a component only cares about a certain set of query strings and wants to update them without affecting the others

E.g. `?q=search+term&sort=top`

If the searchbox only updates the `q` parameter, and I have a separate dropdown component updating the `sort` parameter, I don't want them stepping on each other

**Comment by mattdesl** [comment]
I think the easiest route is just by decoding the query string, modifying it, and then encoding it before using `url-set-query`.

``` js
var setQuery = require('url-set-query')
var qs = require('query-string')
var assign = require('object-assign')
var input = 'http://foo.com/path?q=search+term&sort=top'

// extract
var query = qs.parse(qs.extract(input))

// update
assign(query, {
  q: 'new term'
})

// stringify
var url = setQuery(input, qs.stringify(query))
console.log(url)
```

A small increase in bundle size, but more robust:

``` js
var query = require('url').parse(input, true).query
```

**Comment by cheapsteak** [comment]
:+1:
